# Generated by Django 6.1 on 2026-08-31 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpacePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Discoveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('why_interesting', models.TextField()),
                ('facts', models.JSONField(default=dict)),
                ('source', models.URLField()),
                ('media_type', models.CharField(blank=True, max_length=50, null=True)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('space_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to='api.spaceplan')),
            ],
        ),
    ]
