# Generated by Django 6.1 on 2026-09-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_spaceplan_discoveries'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceplan',
            name='prompt',
            field=models.TextField(default='Legacy plan - prompt not recorded'),
            preserve_default=False,
        ),
    ]
